define({
  root: ({
    _widgetLabel: "Grouped LayerList",
    _featureAction_ShowVertex: "Show Vertex Count",
    label1: "I am a demo widget.",
    label2: "This is configurable.",
    titleBasemap: "Basemaps",
    titleLayers: "Operational layers",
    labelLayer: "Layer name",
    itemZoomTo: "Zoom to",
    itemTransparency: "Transparency",
    itemTransparent: "Transparent",
    itemOpaque: "Opaque",
    itemMoveUp: "Move up",
    itemMoveDown: "Move down",
    itemDesc: "Description",
    itemDownload: "Download",
    itemToAttributeTable: "View in Attribute Table",
    itemShowItemDetails: "Show item details",
    itemChangeSymbology: "Change Layer symbol",
    itemChangeName: "Change Layer Name",
    itemChangeLayerOrder: "Change Layer Order",
    empty: "empty",
    removePopup: "Disable pop-up",
    enablePopup: "Enable pop-up",
    turnAllLayersOff: "Turn all layers off",
    turnAllLayersOn: "Turn all layers on",
    expandAllLayers: "Expand all layers",
    collapseAlllayers: "Collapse all layers",
    turnAllLabelsOff: "Turn all labels off",
    turnAllLabelsOn: "Turn all labels on",
    showLabels: "Toggle labels",
    hideLables: "Hide labels"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 1
});
